spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: false
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:/Users/rabindrasahoo/Documents/h2data
    username: sa
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always

server:
  port: 8000
